### ISSUE TITLE
Time and Space complexities

### ISSUE THREAD

**Issue by msboffl** [msboffl/data-structures-and-algorithms#4]
Write a blog at [msboffl](https://msboffl.com/series/algorithms) for time and space complexities 

**Due date: 03/10/2022**

- [ ] What is a time and space complexity
- [ ] How to calculate time and space complexities

**Comment by Soumyajit2825** [comment]
@msboffl i want to contribute.....can u please tell me in which text editor i have to write this blog??

**Comment by msboffl** [comment]
I have already the readme file, you can add in readme

**Comment by Soumyajit2825** [comment]
> I have already the readme file, you can add in readme

ok sure.

**Comment by Soumyajit2825** [comment]
@msboffl Job DONE
